### ISSUE TITLE
env rendered separately to env.render()

### ISSUE THREAD

**Issue by EndingCredits** [lusob/gym-ple#1]
I may have missed something, but I believe this is undesirable behaviour for the Gym.

For example, the following causes two windows to appear:

``` python
import gym
import gym_ple
env = gym.make('RaycastMaze-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
```

Another issue is that in certain games (eg Flappy Bird)X and y co-ords are flipped when env.render() is called.

**Comment by lusob** [comment]
The rotate problem was due to a bug on getScreenRGB function of PLE package, I have added a hack to fix it.
Regarding to hide the screen, pygame doesn't allow to hide the screen, all I could do is show a black screen and don't render anything on every step.
Thanks for your support @EndingCredits
