### ISSUE TITLE
ERROR on Anaconda(Mac)

### ISSUE THREAD

**Issue by alexxiaoyumao** [lusob/gym-ple#10]
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pygame -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

**Comment by lusob** [comment]
Sorry, right now I haven't a Mac for resolve it but a pulll request with he fix would be very welcomed!
Thanks
