### ISSUE TITLE
Is there a way to close the GUI window once you are done using it?

### ISSUE THREAD

**Issue by ethancaballero** [lusob/gym-ple#6]
`env.close()` does not close the window. I'm looking for line(s) of code that can close the GUI window (without causing the main python program to exit).

**Comment by lusob** [comment]
This is a problem of PLE as you can see in these issues:
https://github.com/ntasfi/PyGame-Learning-Environment/issues/4 
https://github.com/ntasfi/PyGame-Learning-Environment/issues/26
Thanks
