### ISSUE TITLE
Installation Instructions incorrect for OSX

### ISSUE THREAD

**Issue by conquista123** [lusob/gym-ple#7]
Running `conda install -c https://conda.binstar.org/quasiben pygame` returns:

> Fetching package metadata ...
> 
> CondaHTTPError: HTTP None None for url <None>
> Elapsed: None
> 
> An HTTP error occurred when trying to retrieve this URL.
> SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

It looks like the certificate to the link provided is expired.

**Comment by lusob** [comment]
Your are right, it's outdated, you can use:
` conda install -c tlatorre pygame=1.9.2 `
