### ISSUE TITLE
libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by lucasjinreal** [lusob/gym-ple#8]
runing example got this warning and windows have no picture just blank.
I am using MacOS and iterm terminal.

**Comment by boscotsang** [comment]
I also encountered the same problem in Windows system.

**Comment by cxxgtxy** [comment]
Me too, ubuntu.

**Comment by icoxfog417** [comment]
As it is described in the comment on the `example.py`, `env.render()` is not executed to monitor the game.

So if you want to render the game on the screen, comment out `env = Monitor(env, directory=outdir, force=True)` and execute `env.render()` at the gaming loop.

```
for i in range(episode_count):
        ob = env.reset()

        while True:
            action = agent.act(ob, reward, done)
            ob, reward, done, _ = env.step(action)
            env.render()  # render on the screen
            if done:
                break
```
